### ISSUE TITLE
Referenced parameters broken in 3.12.0 (“$ref targets root is not found”)

### ISSUE THREAD

**Issue by tkalliom** [horiuchi/dtsgenerator#503]
The following API specification with paths referencing parameter specifications in the `components` section, adapted from an example in the OpenAPI documentation, produces a `The $ref targets root is not found` error on dtsgenerator 3.12.0. The same specification was successfully processed on 3.11.0.

Specification:
```yaml
openapi: 3.0.0
info:
  title: Referenced parameters example
  version: 0.0.1
  description: Based on https://swagger.io/docs/specification/describing-parameters#common-for-various-paths
components:
  parameters:
    offsetParam:
      in: query
      name: offset
      required: false
      schema:
        type: integer
        minimum: 0
      description: The number of items to skip before starting to collect the result set.
    limitParam:
      in: query
      name: limit
      required: false
      schema:
        type: integer
        minimum: 1
        maximum: 50
        default: 20
      description: The numbers of items to return.
paths:
  /users:
    get:
      summary: Gets a list of users.
      parameters:
        - $ref: '#/components/parameters/offsetParam'
        - $ref: '#/components/parameters/limitParam'
      responses:
        '200':
          description: OK
```

Error:
```
Error: The $ref targets root is not found: #/components/parameters/offsetParam
The $ref targets root is not found: #/components/parameters/limitParam
    at ReferenceResolver.resolve (/tmp/dtsgenerator-parameters/node_modules/dtsgenerator/dist/core/referenceResolver.js:77:19)
    at DtsGenerator.generate (/tmp/dtsgenerator-parameters/node_modules/dtsgenerator/dist/core/dtsGenerator.js:28:29)
    at async Object.dtsGenerator [as default] (/tmp/dtsgenerator-parameters/node_modules/dtsgenerator/dist/core/index.js:15:12)
    at async exec (/tmp/dtsgenerator-parameters/node_modules/dtsgenerator/dist/cli.js:111:20)
```

**Comment by horiuchi** [comment]
@tkalliom Thank you for your report!

I think this cause is the same as this issue #471
I'm working on fixing it now, so please wait a little longer.

**Comment by horiuchi** [comment]
Fixed by #504 
And released by v3.12.1

**Comment by zzzbra** [comment]
Still seeing this issue with what appear to be valid JSON pointer paths.
